miaplicacion/urls.py
from django.urls import path, include
from . import views
from .views import * 

app_name = 'miaplicacion'

urlpatterns = [
    path('', index, name="inicio"),
    path('vendedores/', views.vendedores, name='vendedores'),
    path('compradores/', views.compradores, name='compradores'),
    path('productos/', views.productos, name='productos'),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),


    path('comprador_form/', compradorForm2, name='comprador_form'),
    path('vendedor_form/', vendedorForm2, name='vendedor_form'),
    path('producto_form/', productoForm2, name='producto_form'),

    path('buscar_producto/', buscar_productos, name='buscar_producto'),

]

miproyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #
    path('miaplicacion/', include('miaplicacion.urls')),
]

miaplicacion/models.py
from django.db import models

# Create your models here.

class Vendedor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    correo = models.EmailField(max_length=100)
    telefono = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Comprador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    correo = models.EmailField(max_length=100)
    direccion = models.CharField(max_length=200)
   
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.nombre} - Precio: ${self.precio} - Cantidad: {self.cantidad}"

miaplicacion/forms.py
from django import forms

class compradorForm(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=50, required=True)
    apellido = forms.CharField(label="Apellido", max_length=50, required=True)
    correo = forms.EmailField(label="Correo", max_length=50, required=True)
    direccion = forms.CharField(label="Direccion", max_length=50, required=True)

class vendedorForm(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=50, required=True)
    apellido = forms.CharField(label="Apellido", max_length=50, required=True)
    correo = forms.CharField(label="Correo", max_length=50, required=True)
    telefono = forms.CharField(label="Direccion", max_length=50, required=True)

class productoForm(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=50, required=True)
    precio = forms.IntegerField(label="Precio CLP", required=True)
    cantidad = forms.IntegerField(label="Cantidad", required=True)

class ProductoSearchForm(forms.Form):
    nombre = forms.CharField(required=False, label="Nombre del producto")

miaplicacion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Vendedor, Comprador, Producto
from .forms import *
# Create your views here.

def index(request):
    return render(request, "miaplicacion/base.html")

def vendedores(request):
    vendedores = Vendedor.objects.all()
    ctx = {"vendedores": Vendedor.objects.all()}
    return render(request, 'miaplicacion/vendedores.html', {'vendedores': vendedores})

def compradores(request):
    compradores = Comprador.objects.all()
    ctx = {"compradores": Comprador.objects.all()}
    return render(request, 'miaplicacion/compradores.html', {'compradores': compradores})

def productos(request):
    productos = Producto.objects.all()
    ctx = {"productos": Producto.objects.all()}
    return render(request, 'miaplicacion/productos.html', {'productos': productos})

def compradorForm2(request):
    if request.method == "POST":
        miForm = compradorForm(request.POST)
        print(miForm)
        if miForm.is_valid:
            informacion = miForm.cleaned_data
            comprador = Comprador(nombre=informacion['nombre'], apellido=informacion['apellido'], correo=informacion['correo'], direccion=informacion['direccion'])
            comprador.save()
            return render(request, "miaplicacion/base.html")
    else:
        miForm = compradorForm()

    return render(request, "miaplicacion/compradorForm.html", {"form":miForm})

def vendedorForm2(request):
    if request.method == "POST":
        miForm = vendedorForm(request.POST)
        print(miForm)
        if miForm.is_valid:
            informacion = miForm.cleaned_data
            vendedor = Vendedor(nombre=informacion['nombre'], apellido=informacion['apellido'], correo=informacion['correo'], telefono=informacion['telefono'])
            vendedor.save()
            return render(request, "miaplicacion/base.html")
    else:
        miForm = vendedorForm()

    return render(request, "miaplicacion/vendedorForm.html", {"form":miForm})

def productoForm2(request):
    if request.method == "POST":
        miForm = productoForm(request.POST)
        print(miForm)
        if miForm.is_valid:
            informacion = miForm.cleaned_data
            producto = Producto(nombre=informacion['nombre'], precio=informacion['precio'], cantidad=informacion['cantidad'])
            producto.save()
            return render(request, "miaplicacion/base.html")
    else:
        miForm = productoForm()

    return render(request, "miaplicacion/productoForm.html", {"form":miForm})

def buscar_productos(request):
    form = ProductoSearchForm(request.GET)
    resultados = []

    if form.is_valid():
        nombre = form.cleaned_data.get('nombre', None)
        precio_min = form.cleaned_data.get('precio_min', None)
        precio_max = form.cleaned_data.get('precio_max', None)
        cantidad = form.cleaned_data.get('cantidad', None)

        filtro = {}
        if nombre:
            filtro['nombre__icontains'] = nombre
        if precio_min:
            filtro['precio__gte'] = precio_min
        if precio_max:
            filtro['precio__lte'] = precio_max
        if cantidad:
            filtro['cantidad__gte'] = cantidad
        if filtro:
            resultados = Producto.objects.filter(**filtro)

    mensaje = ""

    if not resultados:
        mensaje = "No se encontraron productos con ese nombre."

    return render(request, 'miaplicacion/buscar_productos.html', {'form': form, 'resultados': resultados, 'mensaje': mensaje})

miaplicacion/templates/miaplicacion/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            
            {% block titulo %}
                Inicio
            {% endblock titulo %}
                
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'miaplicacion/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="#!">Inicio</a>
                <a class="navbar-brand" href="{% url 'miaplicacion:vendedores' %}">Vendedores</a>
                <a class="navbar-brand" href="{% url 'miaplicacion:compradores' %}">Compradores</a>
                <a class="navbar-brand" href="{% url 'miaplicacion:productos' %}">Productos</a>
                <a class="btn btn-primary" href="{% url 'miaplicacion:buscar_productos' %}">Buscar Productos</a>
                <a class="btn btn-primary" href="{% url 'admin:index' %}">Administración</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block cabecera %}
                                Bienvenido a la tercera entrega de L. Silva
                                {% endblock cabecera %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block contenido %}
            
        {% endblock contenido %}


        <!-- Testimonials-->
        <section class="testimonials text-center bg-light">
            <div class="container">
                <h2 class="mb-5">What people are saying...</h2>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="{% static 'miaplicacion/assets/img/testimonials-1.jpg' %}" alt="..." />
                            <h5>Margaret E.</h5>
                            <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="{% static 'miaplicacion/assets/img/testimonials-2.jpg' %}" alt="..." />
                            <h5>Fred S.</h5>
                            <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            <img class="img-fluid rounded-circle mb-3" src="{% static 'miaplicacion/assets/img/testimonials-3.jpg' %}" alt="..." />
                            <h5>Sarah W.</h5>
                            <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Call to Action-->
        <section class="call-to-action text-white text-center" id="signup">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <h2 class="mb-4">Ready to get started? Sign up now!</h2>
                        <!-- Signup form-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form class="form-subscribe" id="contactFormFooter" data-sb-form-api-token="API_TOKEN">
                            <!-- Email address input-->
                            <div class="row">
                                <div class="col">
                                    <input class="form-control form-control-lg" id="emailAddressBelow" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                                    <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:required">Email Address is required.</div>
                                    <div class="invalid-feedback text-white" data-sb-feedback="emailAddressBelow:email">Email Address Email is not valid.</div>
                                </div>
                                <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                            </div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    <p>To activate this form, sign up at</p>
                                    <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'miaplicacion/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

miaplicacion/templates/miaplicacion/buscar_productos.html
<form method="GET">
    {{ form.as_p }}
    <button type="submit">Buscar</button>
</form>

{% if mensaje %}
    <p>{{ mensaje }}</p>
{% else %}
    {% if resultados %}
        <ul>
            {% for producto in resultados %}
                <li>{{ producto.nombre }} - Precio: {{ producto.precio }} - Cantidad: {{ producto.cantidad }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endif %}

miaplicacion/templates/miaplicacion/compradorForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo Comprador</title>
</head>
<body>
    <h2>Registrar Nuevo Comprador</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

miaplicacion/templates/miaplicacion/compradores.html
{% extends 'miaplicacion/base.html' %}
{% load static %}

{% block titulo %}
    Compradores
{% endblock titulo %}

{% block cabecera %}
    Lista de Compradores
{% endblock cabecera %}
    
{% block contenido %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>Direccion</th>
        <tr>
    </thead>
    <tbody>
    {% for Comprador in compradores %}
    <tr>
        <td>{{ Comprador.id }}</td>
        <td>{{ Comprador.nombre }}</td>
        <td>{{ Comprador.apellido }}</td>
        <td>{{ Comprador.correo }}</td>
        <td>{{ Comprador.direccion }}</td>
     </tr>
    {% endfor %}
     </tbody>
     </table>
{% endblock contenido %}

miaplicacion/templates/miaplicacion/productoForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo Comprador</title>
</head>
<body>
    <h2>Ingresar Nuevo Producto</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

miaplicacion/templates/miaplicacion/productos.html
{% extends 'miaplicacion/base.html' %}
{% load static %}


{% block titulo %}
    Productos
{% endblock titulo %}

{% block cabecera %}
    Lista de Productos
{% endblock cabecera %}

{% block contenido %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio $</th>
            <th>Cantidad</th>
        <tr>
    {% for Producto in productos %}
    <tr>
        <td>{{ Producto.id }}</td>
        <td>{{ Producto.nombre }}</td>
        <td>{{ Producto.precio }}</td>
        <td>{{ Producto.cantidad }}</td>
     </tr>
     {% endfor %}
    </tbody>
    </table>
{% endblock contenido %}

miaplicacion/templates/miaplicacion/resultadosProductos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados de Búsqueda</title>
</head>
<body>
    Productos del Inventario {{ producto }}

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Precio $</th>
                <th>Cantidad</th>
            <tr>
        {% for Producto in productos %}
        <tr>
            <td>{{ Producto.id }}</td>
            <td>{{ Producto.nombre }}</td>
            <td>{{ Producto.precio }}</td>
            <td>{{ Producto.cantidad }}</td>
         </tr>
         {% endfor %}
        </tbody>
        </table>    
</body>
</html>

miaplicacion/templates/miaplicacion/vendedorForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo Comprador</title>
</head>
<body>
    <h2>Registrar Nuevo Vendedor</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

miaplicacion/templates/miaplicacion/vendedores.html
{% extends 'miaplicacion/base.html' %}
{% load static %}


{% block titulo %}
    Vendedores
{% endblock titulo %}

{% block cabecera %}
    Lista de Vendedores
{% endblock cabecera %}

{% block contenido %}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>telefono</th>
        <tr>
    </thead>
    <tbody>
    {% for Vendedor in vendedores %}
    <tr>
        <td>{{ Vendedor.id }}</td>
        <td>{{ Vendedor.nombre }}</td>
        <td>{{ Vendedor.apellido }}</td>
        <td>{{ Vendedor.correo }}</td>
        <td>{{ Vendedor.telefono }}</td>
     </tr>
    {% endfor %}  
    </tbody>
    </table>
{% endblock contenido %}